import React from "react";

export const metadata = {
  title:
    "Gallery - Portal Informasi Acara & Seminar Fakultas Teknik Universitas Islam Riau",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
      <h1>Ini galeri</h1>
    </div>
  );
}
