### get all mahasiswa
GET http://localhost:3000/api/mahasiswa

### get one mahasiswa
GET http://localhost:3000/api/mahasiswa/login

### add data mahasiswa
POST http://localhost:3000/api/mahasiswa
Content-Type: application/json
Authorization: 122

{
    "npm": "20351055",
    "password": "122"
}

### edit data mahasiswa
PUT http://localhost:3000/api/mahasiswa/CN3wEug8oFqh3j3AA6NO
Content-Type: application/json

{
    "nama": "geri",
    "npm": "203510345",
    "email": "geri@gmail.com",
    "password": "2323232323"
}

### delete data mahasiswa
DELETE  http://localhost:3000/api/mahasiswa/Za9d7vnlTnPTJtzwkUyG
