### get all acara
GET http://localhost:3000/api/acara

### get one acara
GET http://localhost:3000/api/acara/ET23Qyk5v55yk2C9pncP

### add data acara
POST http://localhost:3000/api/acara
Content-Type: application/json

{
    "judul": "acara bla bla bla",
    "deskripsi": "ini deskripsi",
    "kategori": "ini kategori",
    "prodi": "ini prodi",
    "waktu_mulai": "ini waktu_mulai",
    "waktu_selesai": "ini waktu_selesai",
    "tempat": "ini tempat",
    "gambar": "ini gambar"
}

### edit data acara
PUT http://localhost:3000/api/acara/ET23Qyk5v55yk2C9pncP
Content-Type: application/json

{
    "judul": "webinar bla bla bla",
    "deskripsi": "ini deskripsi",
    "kategori": "ini kategori",
    "prodi": "ini prodi",
    "waktu_mulai": "ini waktu_mulai",
    "waktu_selesai": "ini waktu_selesai",
    "tempat": "ini tempat",
    "gambar": "ini gambar"
}

### delete data acara
DELETE  http://localhost:3000/api/acara/N854siADsq2N8pb03DJ1
