
### register portal
POST http://localhost:3000/api/auth/portal-register
Content-Type: application/json

{
    "npm": "203510358",
    "email": "iwal@gmail.com",
    "password": "12345",
    "confirmPassword": "12345",
    "nama": "iwal",
    "prodi":"Teknik Mesin"
}

### login portal
POST http://localhost:3000/api/auth/portal-login
Content-Type: application/json

{
    "npm": "203510999",
    "password": "123456"
}