### get all mahasiswa
GET http://localhost:3000/api/mahasiswa

### get one mahasiswa
GET http://localhost:3000/api/mahasiswa/Ghg2qXlMaXNqkhBbYPmM

### add data mahasiswa
POST http://localhost:3000/api/mahasiswa
Content-Type: application/json

{
    "npm": "20351055",
    "password": "122"
}

### edit data mahasiswa
PUT http://localhost:3000/api/mahasiswa/Ghg2qXlMaXNqkhBbYPmM
Content-Type: application/json

{
    "nama": "iwal gege",
    "npm": "203510358",
    "email": "iwal@gmail.com",
    "prodi": "Teknik Mesin"
}

### delete data mahasiswa
DELETE  http://localhost:3000/api/mahasiswa/51LkAbhTX4rrRLnV1DEv

### ubah password mahasiswa
POST http://localhost:3000/api/mahasiswa/Ghg2qXlMaXNqkhBbYPmM/change-password
Content-Type: application/json

{
    "oldPassword": "12345",
    "newPassword": "12345"
}