import Contact from "@/components/Contact";
import React from "react";

export const metadata = {
  title:
    "Contact - Portal Informasi Acara & Seminar Fakultas Teknik Universitas Islam Riau",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="">
      <Contact />
    </div>
  );
}
