import React from "react";

export const metadata = {
  title:
    "Semua Acara - Portal Informasi Acara & Seminar Fakultas Teknik Universitas Islam Riau",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
      <h3 className="text-2xl font-bold text-center">All Events</h3>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam corrupti
      eligendi tenetur rerum. Necessitatibus voluptas sapiente alias deleniti,
      beatae quae nesciunt soluta eos, ab harum laboriosam autem nobis ut
      quisquam!
    </div>
  );
}
